import { Router } from 'express';
import { register, verifyOtp, resendOtp, login, forgotPassword, resetPassword, me, updateProfile, changePassword, adminBootstrap } from '../controllers/authController.js';
import { protect, requireRole } from '../middleware/auth.js';
import { uploadImage } from '../middleware/upload.js';
const router=Router();
router.post('/register', uploadImage.single('avatar'), register);
router.post('/verify-otp', verifyOtp);
router.post('/resend-otp', resendOtp);
router.post('/login', login);
router.post('/forgot-password', forgotPassword);
router.post('/reset-password', resetPassword);
router.post('/bootstrap-admin', adminBootstrap);
router.get('/me', protect, me);
router.put('/profile', protect, uploadImage.single('avatar'), updateProfile);
router.put('/change-password', protect, changePassword);
export default router;
