import { Router } from 'express';
import * as c from '../controllers/bookingController.js';
import { protect } from '../middleware/auth.js';
const router=Router();
router.get('/availability', c.availability);
router.post('/', protect, c.create);
router.get('/', protect, c.list);
router.get('/:id/payments', protect, c.payments);
router.post('/:id/payments', protect, c.addPayment);
router.get('/:id', protect, c.getOne);
router.put('/:id', protect, c.update);
router.delete('/:id', protect, c.remove);
export default router;
