import { Router } from 'express';
import * as c from '../controllers/messageController.js';
import { protect } from '../middleware/auth.js';
const router=Router();
router.get('/', protect, c.conversations);
router.post('/', protect, c.createConversation);
router.get('/:id/messages', protect, c.getMessages);
router.post('/:id/messages', protect, c.sendMessage);
router.put('/:id/read', protect, c.markRead);
export default router;
