import { DataTypes } from 'sequelize';
import { sequelize } from '../config/db.js';

const Booking = sequelize.define('Booking', {
  reference: { type: DataTypes.STRING(20), unique: true }, // SGH-1092 style, generated by the server

  guestName: { type: DataTypes.STRING(150), allowNull: false },
  guestEmail: { type: DataTypes.STRING(150), allowNull: false, validate: { isEmail: true } },
  guestPhone: { type: DataTypes.STRING(50), allowNull: false },
  guestAvatar: { type: DataTypes.STRING(500) },

  // roomId (foreign key) is added by the Room <-> Booking relation in models/index.js.
  // The room name/type/number are copied here so old bookings keep their data
  // even if the room is edited or deleted later.
  roomName: { type: DataTypes.STRING(150), allowNull: false },
  roomType: { type: DataTypes.STRING(100) },
  roomNumber: { type: DataTypes.STRING(20) },

  checkIn: { type: DataTypes.DATEONLY, allowNull: false },
  checkOut: { type: DataTypes.DATEONLY, allowNull: false },
  adults: { type: DataTypes.INTEGER, defaultValue: 1, validate: { min: 1 } },
  children: { type: DataTypes.INTEGER, defaultValue: 0, validate: { min: 0 } },

  amount: { type: DataTypes.DECIMAL(10, 2), defaultValue: 0 },
  paymentStatus: { type: DataTypes.STRING(50), defaultValue: 'Pending' }, // Paid in Full, Deposit Paid (50%), Refunded ...
  status: {
    type: DataTypes.ENUM('Pending', 'Confirmed', 'Checked In', 'Completed', 'Cancelled'),
    defaultValue: 'Pending',
  },
  requests: { type: DataTypes.TEXT },
});

export default Booking;
